// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "RHBaseMessage.pb.h"
// @@protoc_insertion_point(imports)

@implementation RhbaseMessageRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [RhbaseMessageRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface RHBaseMessage ()
@property SInt32 protobufType;
@property (strong) NSString* protobufClassName;
@property (strong) NSData* protobufData;
@end

@implementation RHBaseMessage

- (BOOL) hasProtobufType {
  return !!hasProtobufType_;
}
- (void) setHasProtobufType:(BOOL) _value_ {
  hasProtobufType_ = !!_value_;
}
@synthesize protobufType;
- (BOOL) hasProtobufClassName {
  return !!hasProtobufClassName_;
}
- (void) setHasProtobufClassName:(BOOL) _value_ {
  hasProtobufClassName_ = !!_value_;
}
@synthesize protobufClassName;
- (BOOL) hasProtobufData {
  return !!hasProtobufData_;
}
- (void) setHasProtobufData:(BOOL) _value_ {
  hasProtobufData_ = !!_value_;
}
@synthesize protobufData;
- (instancetype) init {
  if ((self = [super init])) {
    self.protobufType = 0;
    self.protobufClassName = @"";
    self.protobufData = [NSData data];
  }
  return self;
}
static RHBaseMessage* defaultRHBaseMessageInstance = nil;
+ (void) initialize {
  if (self == [RHBaseMessage class]) {
    defaultRHBaseMessageInstance = [[RHBaseMessage alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultRHBaseMessageInstance;
}
- (instancetype) defaultInstance {
  return defaultRHBaseMessageInstance;
}
- (BOOL) isInitialized {
  if (!self.hasProtobufClassName) {
    return NO;
  }
  if (!self.hasProtobufData) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasProtobufType) {
    [output writeInt32:1 value:self.protobufType];
  }
  if (self.hasProtobufClassName) {
    [output writeString:2 value:self.protobufClassName];
  }
  if (self.hasProtobufData) {
    [output writeData:3 value:self.protobufData];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasProtobufType) {
    size_ += computeInt32Size(1, self.protobufType);
  }
  if (self.hasProtobufClassName) {
    size_ += computeStringSize(2, self.protobufClassName);
  }
  if (self.hasProtobufData) {
    size_ += computeDataSize(3, self.protobufData);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (RHBaseMessage*) parseFromData:(NSData*) data {
  return (RHBaseMessage*)[[[RHBaseMessage builder] mergeFromData:data] build];
}
+ (RHBaseMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RHBaseMessage*)[[[RHBaseMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RHBaseMessage*) parseFromInputStream:(NSInputStream*) input {
  return (RHBaseMessage*)[[[RHBaseMessage builder] mergeFromInputStream:input] build];
}
+ (RHBaseMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RHBaseMessage*)[[[RHBaseMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RHBaseMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RHBaseMessage*)[[[RHBaseMessage builder] mergeFromCodedInputStream:input] build];
}
+ (RHBaseMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RHBaseMessage*)[[[RHBaseMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RHBaseMessageBuilder*) builder {
  return [[RHBaseMessageBuilder alloc] init];
}
+ (RHBaseMessageBuilder*) builderWithPrototype:(RHBaseMessage*) prototype {
  return [[RHBaseMessage builder] mergeFrom:prototype];
}
- (RHBaseMessageBuilder*) builder {
  return [RHBaseMessage builder];
}
- (RHBaseMessageBuilder*) toBuilder {
  return [RHBaseMessage builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasProtobufType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"protobufType", [NSNumber numberWithInteger:self.protobufType]];
  }
  if (self.hasProtobufClassName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"protobufClassName", self.protobufClassName];
  }
  if (self.hasProtobufData) {
    [output appendFormat:@"%@%@: %@\n", indent, @"protobufData", self.protobufData];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasProtobufType) {
    [dictionary setObject: [NSNumber numberWithInteger:self.protobufType] forKey: @"protobufType"];
  }
  if (self.hasProtobufClassName) {
    [dictionary setObject: self.protobufClassName forKey: @"protobufClassName"];
  }
  if (self.hasProtobufData) {
    [dictionary setObject: self.protobufData forKey: @"protobufData"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[RHBaseMessage class]]) {
    return NO;
  }
  RHBaseMessage *otherMessage = other;
  return
      self.hasProtobufType == otherMessage.hasProtobufType &&
      (!self.hasProtobufType || self.protobufType == otherMessage.protobufType) &&
      self.hasProtobufClassName == otherMessage.hasProtobufClassName &&
      (!self.hasProtobufClassName || [self.protobufClassName isEqual:otherMessage.protobufClassName]) &&
      self.hasProtobufData == otherMessage.hasProtobufData &&
      (!self.hasProtobufData || [self.protobufData isEqual:otherMessage.protobufData]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasProtobufType) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.protobufType] hash];
  }
  if (self.hasProtobufClassName) {
    hashCode = hashCode * 31 + [self.protobufClassName hash];
  }
  if (self.hasProtobufData) {
    hashCode = hashCode * 31 + [self.protobufData hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface RHBaseMessageBuilder()
@property (strong) RHBaseMessage* resultRhbaseMessage;
@end

@implementation RHBaseMessageBuilder
@synthesize resultRhbaseMessage;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultRhbaseMessage = [[RHBaseMessage alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultRhbaseMessage;
}
- (RHBaseMessageBuilder*) clear {
  self.resultRhbaseMessage = [[RHBaseMessage alloc] init];
  return self;
}
- (RHBaseMessageBuilder*) clone {
  return [RHBaseMessage builderWithPrototype:resultRhbaseMessage];
}
- (RHBaseMessage*) defaultInstance {
  return [RHBaseMessage defaultInstance];
}
- (RHBaseMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RHBaseMessage*) buildPartial {
  RHBaseMessage* returnMe = resultRhbaseMessage;
  self.resultRhbaseMessage = nil;
  return returnMe;
}
- (RHBaseMessageBuilder*) mergeFrom:(RHBaseMessage*) other {
  if (other == [RHBaseMessage defaultInstance]) {
    return self;
  }
  if (other.hasProtobufType) {
    [self setProtobufType:other.protobufType];
  }
  if (other.hasProtobufClassName) {
    [self setProtobufClassName:other.protobufClassName];
  }
  if (other.hasProtobufData) {
    [self setProtobufData:other.protobufData];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RHBaseMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RHBaseMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setProtobufType:[input readInt32]];
        break;
      }
      case 18: {
        [self setProtobufClassName:[input readString]];
        break;
      }
      case 26: {
        [self setProtobufData:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasProtobufType {
  return resultRhbaseMessage.hasProtobufType;
}
- (SInt32) protobufType {
  return resultRhbaseMessage.protobufType;
}
- (RHBaseMessageBuilder*) setProtobufType:(SInt32) value {
  resultRhbaseMessage.hasProtobufType = YES;
  resultRhbaseMessage.protobufType = value;
  return self;
}
- (RHBaseMessageBuilder*) clearProtobufType {
  resultRhbaseMessage.hasProtobufType = NO;
  resultRhbaseMessage.protobufType = 0;
  return self;
}
- (BOOL) hasProtobufClassName {
  return resultRhbaseMessage.hasProtobufClassName;
}
- (NSString*) protobufClassName {
  return resultRhbaseMessage.protobufClassName;
}
- (RHBaseMessageBuilder*) setProtobufClassName:(NSString*) value {
  resultRhbaseMessage.hasProtobufClassName = YES;
  resultRhbaseMessage.protobufClassName = value;
  return self;
}
- (RHBaseMessageBuilder*) clearProtobufClassName {
  resultRhbaseMessage.hasProtobufClassName = NO;
  resultRhbaseMessage.protobufClassName = @"";
  return self;
}
- (BOOL) hasProtobufData {
  return resultRhbaseMessage.hasProtobufData;
}
- (NSData*) protobufData {
  return resultRhbaseMessage.protobufData;
}
- (RHBaseMessageBuilder*) setProtobufData:(NSData*) value {
  resultRhbaseMessage.hasProtobufData = YES;
  resultRhbaseMessage.protobufData = value;
  return self;
}
- (RHBaseMessageBuilder*) clearProtobufData {
  resultRhbaseMessage.hasProtobufData = NO;
  resultRhbaseMessage.protobufData = [NSData data];
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
